name: ruff and mypy

on: 
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ ai ]

jobs:
  lint-training:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./training

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup
        uses: actions/setup-python@v5
        with: 
          python-version: "3.13.7"
          cache: "pip"

      - name: pip 
        run: pip install .

      - name: ruff
        run: ruff check .

      - name: mypy
        run: mypy .

  # lint-inference:
  #     runs-on: ubuntu-latest
  #     defaults:
  #       run:
  #         working-directory: ./inference

  #     steps:
  #       - name: checkout
  #         uses: actions/checkout@v5

  #       - name: setup
  #         uses: actions/setup-python@v5
  #         with: 
  #           python-version: "3.13.7"
  #           cache: "pip"

  #       - name: pip 
  #         run: pip install .

  #       - name: ruff
  #         run: ruff check .

  #       - name: mypy
  #         run: mypy .
